
#include "oordb.ch"

CLASS Table1 FROM TTable
PROTECTED:
    DEFINE FIELDS
    DEFINE PRIMARY INDEX

PUBLIC:

    DATA TableFileName INIT "table1"

ENDCLASS

/*
    FIELDS
*/
BEGIN FIELDS CLASS Table1

    ADD AUTOINC FIELD "_id"

    ADD STRING FIELD "STR1" SIZE 10
    ADD STRING FIELD "STR2" SIZE 10
    ADD STRING FIELD "STR3" SIZE 10
    ADD STRING FIELD "STR4" SIZE 10
    ADD STRING FIELD "STR5" SIZE 10
    ADD STRING FIELD "STR6" SIZE 10
    ADD STRING FIELD "STR7" SIZE 10
    ADD STRING FIELD "STR8" SIZE 10
    ADD STRING FIELD "STR9" SIZE 10

END FIELDS CLASS

BEGIN PRIMARY INDEX CLASS Table1
    DEFINE INDEX "Primary" KEYFIELD "_id"
END PRIMARY INDEX CLASS
